services:
  - type: web
    name: my-n8n-instance
    runtime: docker
    repo: https://github.com
    plan: free
    region: singapore
    envVars:
      - key: N8N_SECURE_COOKIE
        value: "false"
    disk:
      name: n8n-storage
      mountPath: /home/node/.n8n
      sizeGB: 1
